export const keywords = [
  "anime",
  "watch anime",
  "anime watch",
  "anime watch online",
  "anime watch online free",
  "Watch anime for free",
  "Free anime streaming",
  "Anime online streaming",
  "Anime series free",
  "Watch anime episodes",
  "Anime watch online",
  "Free anime sites",
  "Anime streaming websites",
  "Stream anime legally",
  "Watch anime dubbed",
  "Watch subbed anime",
  "Anime movies online free",
  "Anime genres to watch",
  "Best anime to watch",
  "New anime releases",
  "Anime recommendations",
  "Anime watchlist",
  "Anime reviews",
  "Top anime series",
  "Anime fan community",
  "Anime streaming platforms",
  "Watch anime without ads",
  "Free anime apps",
  "Where to watch anime online",
  "Anime binge-watch",
  "Where to watch anime online for free",
  "Best websites to stream anime for free",
  "How to watch anime without paying",
  "Watch anime online free with English subtitles",
  "Free anime streaming sites for popular series",
  "Watch classic anime series online free",
  "Top platforms to watch anime free of charge",
  "Free streaming options for new anime releases",
  "Legal websites to watch anime online free",
  "Anime streaming apps that are free to use",
  "Watch anime episodes online without ads",
  "Best free apps for streaming anime",
  "Free anime sites with no sign-up required",
  "Watch anime movies online for free in HD",
  "Find free anime streaming services easily",
  "Watch dubbed anime online for free",
  "Best anime to watch online for free",
  "Free anime streaming for kids and families",
  "Where to find free anime content to stream",
  "Watch the latest anime episodes online for free",
  "I love to watch anime online for free during weekends.",
  "Have you tried any free anime streaming websites?",
  "My favorite way to watch anime is on platforms that offer free streaming.",
  "I often look for sites where I can watch anime episodes without a subscription.",
  "Do you know any good free apps to watch anime?",
  "I prefer watching anime with English subtitles for a better experience.",
  "Finding a legal site to stream anime for free can be challenging.",
  "During summer breaks, I binge-watch classic anime series online for free.",
  "There are many great websites that allow you to watch anime without ads.",
  "I often search for new anime releases to watch online without paying.",
];
